/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_autopieces_cpp_MoveMethod */

#ifndef _Included_com_example_autopieces_cpp_MoveMethod
#define _Included_com_example_autopieces_cpp_MoveMethod
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_autopieces_cpp_MoveMethod
 * Method:    calculateMovePath
 * Signature: (IIII[III)[I
 */
JNIEXPORT jintArray JNICALL Java_com_example_autopieces_cpp_MoveMethod_calculateMovePath
  (JNIEnv *, jclass, jint, jint, jint, jint, jintArray, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
